export type ProductRarity = 'COMMON' | 'RARE' | 'EPIC'
export type ProductCategory = 'reward' | 'gear' | 'learning' | 'wellness' | 'premium'

export interface Product {
  id: string
  name: string
  description: string
  emoji: string
  category: ProductCategory
  pointCost: number
  rarity: ProductRarity
  digital: boolean
  downloadPath?: string
}

export const PRODUCTS: Product[] = [
  {
    id: 'breathing-guide',
    name: 'Pranayama Guide PDF',
    description: 'Illustrated breathing techniques for beginners to advanced practitioners.',
    emoji: '💨',
    category: 'learning',
    pointCost: 25,
    rarity: 'COMMON',
    digital: true,
    downloadPath: '/downloads/pranayama-guide.pdf',
  },
  {
    id: 'morning-poster',
    name: 'Morning Yoga Poster',
    description: 'Printable A3 poster of the perfect sunrise flow sequence.',
    emoji: '🌅',
    category: 'learning',
    pointCost: 40,
    rarity: 'COMMON',
    digital: true,
  },
  {
    id: 'meditation-playlist',
    name: 'Meditation Music Pack',
    description: 'Curated ambient tracks for deep meditation and savasana.',
    emoji: '🎵',
    category: 'wellness',
    pointCost: 60,
    rarity: 'COMMON',
    digital: true,
  },
  {
    id: 'yoga-days-3',
    name: '3 Bonus Yoga Days',
    description: 'Add 3 free yoga days to your account instantly.',
    emoji: '💚',
    category: 'reward',
    pointCost: 75,
    rarity: 'COMMON',
    digital: true,
  },
  {
    id: 'incense-set',
    name: 'Incense Stick Set',
    description: 'Calming sandalwood and lavender incense for your practice space.',
    emoji: '🪷',
    category: 'wellness',
    pointCost: 100,
    rarity: 'COMMON',
    digital: false,
  },
  {
    id: 'yoga-towel',
    name: 'Yoga Towel',
    description: 'Non-slip microfiber towel for your practice.',
    emoji: '🎽',
    category: 'gear',
    pointCost: 150,
    rarity: 'COMMON',
    digital: false,
  },
  {
    id: 'scented-candle',
    name: 'Scented Candle',
    description: 'Hand-poured soy candle with calming jasmine and cedarwood.',
    emoji: '🕯️',
    category: 'wellness',
    pointCost: 175,
    rarity: 'COMMON',
    digital: false,
  },
  {
    id: 'foam-block',
    name: 'Foam Yoga Block',
    description: 'High-density foam block for alignment and support.',
    emoji: '🧱',
    category: 'gear',
    pointCost: 200,
    rarity: 'COMMON',
    digital: false,
  },
  {
    id: 'herbal-tea',
    name: 'Herbal Tea Sampler',
    description: 'Assorted herbal teas for post-practice recovery and calm.',
    emoji: '🫖',
    category: 'wellness',
    pointCost: 225,
    rarity: 'COMMON',
    digital: false,
  },
  {
    id: 'beginners-guide',
    name: "Yoga Beginner's Guide",
    description: 'Step-by-step illustrated guide for new practitioners.',
    emoji: '📖',
    category: 'learning',
    pointCost: 250,
    rarity: 'COMMON',
    digital: false,
  },
  {
    id: 'strap-set',
    name: 'Yoga Strap Set',
    description: 'Adjustable cotton straps to deepen stretches safely.',
    emoji: '🎀',
    category: 'gear',
    pointCost: 300,
    rarity: 'RARE',
    digital: false,
  },
  {
    id: 'ayurvedic-oil',
    name: 'Ayurvedic Massage Oil',
    description: 'Traditional herbal oil blend for post-practice recovery.',
    emoji: '💆',
    category: 'wellness',
    pointCost: 350,
    rarity: 'RARE',
    digital: false,
  },
  {
    id: 'essential-oils',
    name: 'Essential Oil Set',
    description: 'Lavender & eucalyptus oils for post-practice relaxation.',
    emoji: '🌿',
    category: 'wellness',
    pointCost: 400,
    rarity: 'RARE',
    digital: false,
  },
  {
    id: 'resistance-bands',
    name: 'Resistance Band Set',
    description: 'Three resistance levels for strength training and stretching.',
    emoji: '💪',
    category: 'gear',
    pointCost: 450,
    rarity: 'RARE',
    digital: false,
  },
  {
    id: 'premium-mat',
    name: 'Premium Yoga Mat',
    description: 'Eco-friendly natural rubber mat with alignment lines.',
    emoji: '🧘',
    category: 'gear',
    pointCost: 500,
    rarity: 'RARE',
    digital: false,
  },
  {
    id: 'week-classes',
    name: '1-Week Free Classes',
    description: 'Unlimited access to live & recorded yoga classes for 7 days.',
    emoji: '🌟',
    category: 'premium',
    pointCost: 600,
    rarity: 'EPIC',
    digital: true,
  },
  {
    id: 'yoga-bag',
    name: 'Yoga Carry Bag',
    description: 'Spacious canvas tote with mat strap and inner pockets.',
    emoji: '👜',
    category: 'gear',
    pointCost: 700,
    rarity: 'EPIC',
    digital: false,
  },
  {
    id: 'month-pass',
    name: '1-Month Premium Pass',
    description: 'Full premium membership — classes, workshops & more for 30 days.',
    emoji: '🏆',
    category: 'premium',
    pointCost: 1000,
    rarity: 'EPIC',
    digital: true,
  },
]
